export const mockedMovies = [
	{
		adult: false,
		id: 2,
		original_title: 'Ariel',
		popularity: 7.724,
		video: false,
	},
	{
		adult: false,
		id: 3,
		original_title: 'Varjoja paratiisissa',
		popularity: 7.745,
		video: false,
	},
	{
		adult: false,
		id: 5,
		original_title: 'Four Rooms',
		popularity: 14.779,
		video: false,
	},
	{
		adult: false,
		id: 6,
		original_title: 'Judgment Night',
		popularity: 11.34,
		video: false,
	},
	{
		adult: false,
		id: 8,
		original_title: 'Life in Loops (A Megacities RMX)',
		popularity: 1.987,
		video: false,
	},
	{
		adult: false,
		id: 9,
		original_title: 'Sonntag im August',
		popularity: 1.628,
		video: false,
	},
	{
		adult: false,
		id: 11,
		original_title: 'Star Wars',
		popularity: 62.433,
		video: false,
	},
	{
		adult: false,
		id: 12,
		original_title: 'Finding Nemo',
		popularity: 130.136,
		video: false,
	},
	{
		adult: false,
		id: 13,
		original_title: 'Forrest Gump',
		popularity: 65.545,
		video: false,
	},
	{
		adult: false,
		id: 14,
		original_title: 'American Beauty',
		popularity: 30.447,
		video: false,
	},
	{
		adult: false,
		id: 15,
		original_title: 'Citizen Kane',
		popularity: 21.342,
		video: false,
	},
	{
		adult: false,
		id: 16,
		original_title: 'Dancer in the Dark',
		popularity: 15.817,
		video: false,
	},
	{
		adult: false,
		id: 17,
		original_title: 'The Dark',
		popularity: 6.861,
		video: false,
	},
	{
		adult: false,
		id: 18,
		original_title: 'The Fifth Element',
		popularity: 45.321,
		video: false,
	},
	{
		adult: false,
		id: 19,
		original_title: 'Metropolis',
		popularity: 21.622,
		video: false,
	},
	{
		adult: false,
		id: 20,
		original_title: 'My Life Without Me',
		popularity: 14.321,
		video: false,
	},
	{
		adult: false,
		id: 21,
		original_title: 'The Endless Summer',
		popularity: 6.996,
		video: false,
	},
	{
		adult: false,
		id: 22,
		original_title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
		popularity: 129.058,
		video: false,
	},
	{
		adult: false,
		id: 24,
		original_title: 'Kill Bill: Vol. 1',
		popularity: 43.157,
		video: false,
	},
	{
		adult: false,
		id: 25,
		original_title: 'Jarhead',
		popularity: 22.621,
		video: false,
	},
	{
		adult: false,
		id: 26,
		original_title: 'LaLehet Al HaMayim',
		popularity: 5.443,
		video: false,
	},
	{
		adult: false,
		id: 27,
		original_title: '9 Songs',
		popularity: 32.477,
		video: false,
	},
	{
		adult: false,
		id: 28,
		original_title: 'Apocalypse Now',
		popularity: 32.315,
		video: false,
	},
	{
		adult: false,
		id: 33,
		original_title: 'Unforgiven',
		popularity: 26.152,
		video: false,
	},
	{
		adult: false,
		id: 35,
		original_title: 'The Simpsons Movie',
		popularity: 118.866,
		video: false,
	},
	{
		adult: false,
		id: 38,
		original_title: 'Eternal Sunshine of the Spotless Mind',
		popularity: 39.49,
		video: false,
	},
	{
		adult: false,
		id: 55,
		original_title: 'Amores perros',
		popularity: 31.673,
		video: false,
	},
	{
		adult: false,
		id: 58,
		original_title: "Pirates of the Caribbean: Dead Man's Chest",
		popularity: 130.029,
		video: false,
	},
	{
		adult: false,
		id: 59,
		original_title: 'A History of Violence',
		popularity: 14.443,
		video: false,
	},
	{
		adult: false,
		id: 62,
		original_title: '2001: A Space Odyssey',
		popularity: 34.776,
		video: false,
	},
	{
		adult: false,
		id: 63,
		original_title: 'Twelve Monkeys',
		popularity: 26.97,
		video: false,
	},
	{
		adult: false,
		id: 64,
		original_title: 'Hable con ella',
		popularity: 22.021,
		video: false,
	},
	{
		adult: false,
		id: 65,
		original_title: '8 Mile',
		popularity: 62.92,
		video: false,
	},
	{
		adult: false,
		id: 66,
		original_title: 'Absolute Power',
		popularity: 16.4,
		video: false,
	},
	{
		adult: false,
		id: 67,
		original_title: 'Paradise Now',
		popularity: 7.787,
		video: false,
	},
	{
		adult: false,
		id: 68,
		original_title: 'Brazil',
		popularity: 15.496,
		video: false,
	},
	{
		adult: false,
		id: 69,
		original_title: 'Walk the Line',
		popularity: 18.542,
		video: false,
	},
	{
		adult: false,
		id: 70,
		original_title: 'Million Dollar Baby',
		popularity: 27.999,
		video: false,
	},
	{
		adult: false,
		id: 71,
		original_title: 'Billy Elliot',
		popularity: 21.355,
		video: false,
	},
	{
		adult: false,
		id: 73,
		original_title: 'American History X',
		popularity: 40.053,
		video: false,
	},
	{
		adult: false,
		id: 74,
		original_title: 'War of the Worlds',
		popularity: 53.494,
		video: false,
	},
	{
		adult: false,
		id: 75,
		original_title: 'Mars Attacks!',
		popularity: 23.712,
		video: false,
	},
	{
		adult: false,
		id: 76,
		original_title: 'Before Sunrise',
		popularity: 17.605,
		video: false,
	},
	{
		adult: false,
		id: 77,
		original_title: 'Memento',
		popularity: 27.408,
		video: false,
	},
	{
		adult: false,
		id: 78,
		original_title: 'Blade Runner',
		popularity: 40.404,
		video: false,
	},
	{
		adult: false,
		id: 79,
		original_title: '英雄',
		popularity: 26.036,
		video: false,
	},
	{
		adult: false,
		id: 80,
		original_title: 'Before Sunset',
		popularity: 18.643,
		video: false,
	},
	{
		adult: false,
		id: 81,
		original_title: '風の谷のナウシカ',
		popularity: 34.355,
		video: false,
	},
	{
		adult: false,
		id: 82,
		original_title: 'Miami Vice',
		popularity: 18.942,
		video: false,
	},
	{
		adult: false,
		id: 83,
		original_title: 'Open Water',
		popularity: 19.272,
		video: false,
	},
	{
		adult: false,
		id: 85,
		original_title: 'Raiders of the Lost Ark',
		popularity: 39.587,
		video: false,
	},
	{
		adult: false,
		id: 86,
		original_title: 'Elementarteilchen',
		popularity: 7.229,
		video: false,
	},
	{
		adult: false,
		id: 87,
		original_title: 'Indiana Jones and the Temple of Doom',
		popularity: 28.548,
		video: false,
	},
	{
		adult: false,
		id: 88,
		original_title: 'Dirty Dancing',
		popularity: 23.414,
		video: false,
	},
	{
		adult: false,
		id: 89,
		original_title: 'Indiana Jones and the Last Crusade',
		popularity: 34.878,
		video: false,
	},
	{
		adult: false,
		id: 90,
		original_title: 'Beverly Hills Cop',
		popularity: 25.03,
		video: false,
	},
	{
		adult: false,
		id: 91,
		original_title: 'Las Hurdes',
		popularity: 7.214,
		video: false,
	},
	{
		adult: false,
		id: 92,
		original_title: 'Megacities',
		popularity: 1.241,
		video: false,
	},
	{
		adult: false,
		id: 93,
		original_title: 'Anatomy of a Murder',
		popularity: 10.996,
		video: false,
	},
	{
		adult: false,
		id: 94,
		original_title: 'Kunstgriff',
		popularity: 0.67,
		video: false,
	},
	{
		adult: false,
		id: 95,
		original_title: 'Armageddon',
		popularity: 59.529,
		video: false,
	},
	{
		adult: false,
		id: 96,
		original_title: 'Beverly Hills Cop II',
		popularity: 23.375,
		video: false,
	},
	{
		adult: false,
		id: 97,
		original_title: 'Tron',
		popularity: 21.58,
		video: false,
	},
	{
		adult: false,
		id: 98,
		original_title: 'Gladiator',
		popularity: 61.678,
		video: false,
	},
	{
		adult: false,
		id: 99,
		original_title: 'Todo sobre mi madre',
		popularity: 16.787,
		video: false,
	},
	{
		adult: false,
		id: 100,
		original_title: 'Lock, Stock and Two Smoking Barrels',
		popularity: 11.808,
		video: false,
	},
];
