export const topRatedMovies = [
  {
    adult: false,
    backdrop_path: '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
    genre_ids: [18, 80],
    id: 238,
    original_language: 'en',
    original_title: 'The Godfather',
    overview:
      'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
    popularity: 95.178,
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    release_date: '1972-03-14',
    title: 'The Godfather',
    video: false,
    vote_average: 8.7,
    vote_count: 16803,
  },
  {
    adult: false,
    backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    genre_ids: [18, 80],
    id: 278,
    original_language: 'en',
    original_title: 'The Shawshank Redemption',
    overview:
      'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
    popularity: 86.716,
    poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    release_date: '1994-09-23',
    title: 'The Shawshank Redemption',
    video: false,
    vote_average: 8.7,
    vote_count: 22530,
  },
  {
    adult: false,
    backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
    genre_ids: [18, 80],
    id: 240,
    original_language: 'en',
    original_title: 'The Godfather Part II',
    overview:
      'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
    popularity: 57.304,
    poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
    release_date: '1974-12-20',
    title: 'The Godfather Part II',
    video: false,
    vote_average: 8.6,
    vote_count: 10181,
  },
  {
    adult: false,
    backdrop_path: '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: 'en',
    original_title: "Schindler's List",
    overview:
      'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
    popularity: 53.885,
    poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    release_date: '1993-12-15',
    title: "Schindler's List",
    video: false,
    vote_average: 8.6,
    vote_count: 13374,
  },
  {
    adult: false,
    backdrop_path: '/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg',
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: 'hi',
    original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
    overview:
      'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
    popularity: 27.118,
    poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
    release_date: '1995-10-19',
    title: 'Dilwale Dulhania Le Jayenge',
    video: false,
    vote_average: 8.6,
    vote_count: 3924,
  },
  {
    adult: false,
    backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: 'ja',
    original_title: '千と千尋の神隠し',
    overview:
      'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
    popularity: 76,
    poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    release_date: '2001-07-20',
    title: 'Spirited Away',
    video: false,
    vote_average: 8.5,
    vote_count: 13469,
  },
  {
    adult: false,
    backdrop_path: '/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg',
    genre_ids: [10751, 18],
    id: 667257,
    original_language: 'es',
    original_title: 'Cosas imposibles',
    overview:
      'Matilde is a woman who, after the death of her husband - a man who constantly abused her - finds her new best friend in Miguel, her young, insecure, disoriented and even dealer neighbor',
    popularity: 8.692,
    poster_path: '/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg',
    release_date: '2021-06-17',
    title: 'Impossible Things',
    video: false,
    vote_average: 8.5,
    vote_count: 271,
  },
  {
    adult: false,
    backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
    genre_ids: [18],
    id: 389,
    original_language: 'en',
    original_title: '12 Angry Men',
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 25.685,
    poster_path: '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
    release_date: '1957-04-10',
    title: '12 Angry Men',
    video: false,
    vote_average: 8.5,
    vote_count: 6751,
  },
  {
    adult: false,
    backdrop_path: '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
    genre_ids: [10749, 16, 18],
    id: 372058,
    original_language: 'ja',
    original_title: '君の名は。',
    overview:
      'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
    popularity: 124.256,
    poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
    release_date: '2016-08-26',
    title: 'Your Name.',
    video: false,
    vote_average: 8.5,
    vote_count: 9166,
  },
  {
    adult: false,
    backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: 'ko',
    original_title: '기생충',
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 61.273,
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    release_date: '2019-05-30',
    title: 'Parasite',
    video: false,
    vote_average: 8.5,
    vote_count: 14600,
  },
  {
    adult: false,
    backdrop_path: '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
    genre_ids: [10749],
    id: 724089,
    original_language: 'en',
    original_title: "Gabriel's Inferno: Part II",
    overview:
      "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
    popularity: 11.429,
    poster_path: '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
    release_date: '2020-07-31',
    title: "Gabriel's Inferno: Part II",
    video: false,
    vote_average: 8.5,
    vote_count: 1439,
  },
  {
    adult: false,
    backdrop_path: '/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg',
    genre_ids: [10749, 16],
    id: 372754,
    original_language: 'ja',
    original_title: '同級生',
    overview:
      'Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.',
    popularity: 12.213,
    poster_path: '/cIfRCA5wEvj9tApca4UDUagQEiM.jpg',
    release_date: '2016-02-20',
    title: 'Dou kyu sei – Classmates',
    video: false,
    vote_average: 8.5,
    vote_count: 257,
  },
  {
    adult: false,
    backdrop_path: '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: 'en',
    original_title: 'The Green Mile',
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 78.418,
    poster_path: '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
    release_date: '1999-12-10',
    title: 'The Green Mile',
    video: false,
    vote_average: 8.5,
    vote_count: 14541,
  },
  {
    adult: false,
    backdrop_path: '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
    genre_ids: [10749],
    id: 696374,
    original_language: 'en',
    original_title: "Gabriel's Inferno",
    overview:
      "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
    popularity: 12.227,
    poster_path: '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
    release_date: '2020-05-29',
    title: "Gabriel's Inferno",
    video: false,
    vote_average: 8.5,
    vote_count: 2293,
  },
  {
    adult: false,
    backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: 'en',
    original_title: 'The Dark Knight',
    overview:
      'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    popularity: 76.037,
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    release_date: '2008-07-14',
    title: 'The Dark Knight',
    video: false,
    vote_average: 8.5,
    vote_count: 28463,
  },
  {
    adult: false,
    backdrop_path: '/v5CEt88iDsuoMaW1Q5Msu9UZdEt.jpg',
    genre_ids: [10749, 18],
    id: 730154,
    original_language: 'ja',
    original_title: 'きみの瞳が問いかけている',
    overview:
      "A tragic accident lead to Kaori's blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori's smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.",
    popularity: 37.453,
    poster_path: '/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg',
    release_date: '2020-10-23',
    title: 'Your Eyes Tell',
    video: false,
    vote_average: 8.5,
    vote_count: 357,
  },
  {
    adult: false,
    backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    genre_ids: [53, 80],
    id: 680,
    original_language: 'en',
    original_title: 'Pulp Fiction',
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 59.387,
    poster_path: '/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg',
    release_date: '1994-09-10',
    title: 'Pulp Fiction',
    video: false,
    vote_average: 8.5,
    vote_count: 23956,
  },
  {
    adult: false,
    backdrop_path: '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
    genre_ids: [37],
    id: 429,
    original_language: 'it',
    original_title: 'Il buono, il brutto, il cattivo',
    overview:
      'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
    popularity: 46.97,
    poster_path: '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
    release_date: '1966-12-23',
    title: 'The Good, the Bad and the Ugly',
    video: false,
    vote_average: 8.5,
    vote_count: 6930,
  },
  {
    adult: false,
    backdrop_path: '/aQ7444JX7gefPhGJTlvilj3zG2S.jpg',
    genre_ids: [10402],
    id: 553512,
    original_language: 'ko',
    original_title: '번 더 스테이지: 더 무비',
    overview:
      'A documentary following the worldwide famous music group BTS, as they tour the world and share their experience along with their beloved band friends and fans.',
    popularity: 18.976,
    poster_path: '/pJKy1yvnKh8UjcuYeG3Rt35xHFA.jpg',
    release_date: '2018-11-15',
    title: 'Burn the Stage: The Movie',
    video: false,
    vote_average: 8.5,
    vote_count: 369,
  },
  {
    adult: false,
    backdrop_path: '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: 'en',
    original_title: 'The Lord of the Rings: The Return of the King',
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    popularity: 125.363,
    poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    release_date: '2003-12-01',
    title: 'The Lord of the Rings: The Return of the King',
    video: false,
    vote_average: 8.5,
    vote_count: 20413,
  },
  {
    adult: false,
    backdrop_path: '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: 'en',
    original_title: 'Forrest Gump',
    overview:
      'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
    popularity: 53.7,
    poster_path: '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
    release_date: '1994-06-23',
    title: 'Forrest Gump',
    video: false,
    vote_average: 8.5,
    vote_count: 23502,
  },
  {
    adult: false,
    backdrop_path: '/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg',
    genre_ids: [10749, 35],
    id: 761053,
    original_language: 'en',
    original_title: "Gabriel's Inferno: Part III",
    overview:
      "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard. Watch Here : https://classic-blog.udn.com/mobile/aaef2970/177226874",
    popularity: 25.412,
    poster_path: '/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg',
    release_date: '2020-11-19',
    title: "Gabriel's Inferno: Part III",
    video: false,
    vote_average: 8.5,
    vote_count: 990,
  },
  {
    adult: false,
    backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
    genre_ids: [18, 80],
    id: 769,
    original_language: 'en',
    original_title: 'GoodFellas',
    overview:
      'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
    popularity: 39.64,
    poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    release_date: '1990-09-12',
    title: 'GoodFellas',
    video: false,
    vote_average: 8.5,
    vote_count: 10609,
  },
  {
    adult: false,
    backdrop_path: '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
    genre_ids: [18, 10749],
    id: 11216,
    original_language: 'it',
    original_title: 'Nuovo Cinema Paradiso',
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    popularity: 17.138,
    poster_path: '/9JhfVOveaY00o8njQu2Xrp4YWud.jpg',
    release_date: '1988-11-17',
    title: 'Cinema Paradiso',
    video: false,
    vote_average: 8.5,
    vote_count: 3491,
  },
  {
    adult: false,
    backdrop_path: '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
    genre_ids: [28, 18],
    id: 346,
    original_language: 'ja',
    original_title: '七人の侍',
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 24.646,
    poster_path: '/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg',
    release_date: '1954-04-26',
    title: 'Seven Samurai',
    video: false,
    vote_average: 8.5,
    vote_count: 2830,
  },
  {
    adult: false,
    backdrop_path: '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
    genre_ids: [35, 18],
    id: 637,
    original_language: 'it',
    original_title: 'La vita è bella',
    overview:
      'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
    popularity: 55.2,
    poster_path: '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
    release_date: '1997-12-20',
    title: 'Life Is Beautiful',
    video: false,
    vote_average: 8.5,
    vote_count: 11400,
  },
  {
    adult: false,
    backdrop_path: '/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg',
    genre_ids: [28, 18, 36],
    id: 14537,
    original_language: 'ja',
    original_title: '切腹',
    overview:
      'Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.',
    popularity: 15.311,
    poster_path: '/w7pWcLaYQkbtRUn99K6ome0DblL.jpg',
    release_date: '1962-09-15',
    title: 'Harakiri',
    video: false,
    vote_average: 8.5,
    vote_count: 688,
  },
  {
    adult: false,
    backdrop_path: '/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg',
    genre_ids: [27, 18, 53],
    id: 539,
    original_language: 'en',
    original_title: 'Psycho',
    overview:
      'When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.',
    popularity: 41.815,
    poster_path: '/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg',
    release_date: '1960-06-22',
    title: 'Psycho',
    video: false,
    vote_average: 8.4,
    vote_count: 8514,
  },
  {
    adult: false,
    backdrop_path: '/uPYa165sraN2c8gZBM9C47g3JoU.jpg',
    genre_ids: [18, 80],
    id: 311,
    original_language: 'en',
    original_title: 'Once Upon a Time in America',
    overview:
      'A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.',
    popularity: 28.418,
    poster_path: '/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg',
    release_date: '1984-05-23',
    title: 'Once Upon a Time in America',
    video: false,
    vote_average: 8.4,
    vote_count: 4389,
  },
  {
    adult: false,
    backdrop_path: '/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg',
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: 'ja',
    original_title: '火垂るの墓',
    overview:
      'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
    popularity: 0.6,
    poster_path: '/qG3RYlIVpTYclR9TYIsy8p7m7AT.jpg',
    release_date: '1988-04-16',
    title: 'Grave of the Fireflies',
    video: false,
    vote_average: 8.4,
    vote_count: 4349,
  },
  {
    adult: false,
    backdrop_path: '/xs6awEGjnH3e36YSAromfYu3PBQ.jpg',
    genre_ids: [35, 18, 14],
    id: 40096,
    original_language: 'pt',
    original_title: 'O Auto da Compadecida',
    overview:
      'The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.',
    popularity: 7.536,
    poster_path: '/imcOp1kJsCsAFCoOtY5OnPrFbAf.jpg',
    release_date: '2000-09-15',
    title: "A Dog's Will",
    video: false,
    vote_average: 8.4,
    vote_count: 925,
  },
  {
    adult: false,
    backdrop_path: '/qUq3QTr2KLvGIcN0GaaaYx9bbyH.jpg',
    genre_ids: [18],
    id: 510,
    original_language: 'en',
    original_title: "One Flew Over the Cuckoo's Nest",
    overview:
      'A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.',
    popularity: 24.992,
    poster_path: '/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg',
    release_date: '1975-11-19',
    title: "One Flew Over the Cuckoo's Nest",
    video: false,
    vote_average: 8.4,
    vote_count: 8911,
  },
  {
    adult: false,
    backdrop_path: '/uBZQOYZLIU9dBmd62fdzBAoropu.jpg',
    genre_ids: [28, 12, 16, 18],
    id: 704264,
    original_language: 'en',
    original_title: 'Primal: Tales of Savagery',
    overview:
      "Genndy Tartakovsky's Primal: Tales of Savagery features a caveman and a dinosaur on the brink of extinction. Bonded by tragedy, this unlikely friendship becomes the only hope of survival.",
    popularity: 29.121,
    poster_path: '/9NBBkdxH0TjQEBSN2AzeE1sgsF9.jpg',
    release_date: '2019-11-21',
    title: 'Primal: Tales of Savagery',
    video: false,
    vote_average: 8.4,
    vote_count: 245,
  },
  {
    adult: false,
    backdrop_path: '/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg',
    genre_ids: [18, 53, 35],
    id: 550,
    original_language: 'en',
    original_title: 'Fight Club',
    overview:
      'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 127.674,
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    release_date: '1999-10-15',
    title: 'Fight Club',
    video: false,
    vote_average: 8.4,
    vote_count: 25050,
  },
  {
    adult: false,
    backdrop_path: '/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg',
    genre_ids: [10749, 16, 14],
    id: 92321,
    original_language: 'ja',
    original_title: '蛍火の杜へ',
    overview:
      'One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...',
    popularity: 0.6,
    poster_path: '/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg',
    release_date: '2011-09-17',
    title: 'Hotarubi no Mori e',
    video: false,
    vote_average: 8.4,
    vote_count: 850,
  },
  {
    adult: false,
    backdrop_path: '/l5K9elugftlcyIHHm4nylvsn26X.jpg',
    genre_ids: [18, 10751],
    id: 255709,
    original_language: 'ko',
    original_title: '소원',
    overview:
      'After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.',
    popularity: 15.509,
    poster_path: '/1xXaGHQYZGh1RBjP8yTl7vjW6qZ.jpg',
    release_date: '2013-10-02',
    title: 'Hope',
    video: false,
    vote_average: 8.4,
    vote_count: 445,
  },
  {
    adult: false,
    backdrop_path: '/5p3aTxtUtZHCHwYsuycutmxIhND.jpg',
    genre_ids: [18, 80],
    id: 598,
    original_language: 'pt',
    original_title: 'Cidade de Deus',
    overview:
      "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    popularity: 37.242,
    poster_path: '/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg',
    release_date: '2002-02-05',
    title: 'City of God',
    video: false,
    vote_average: 8.4,
    vote_count: 6064,
  },
  {
    adult: false,
    backdrop_path: '/9LuL3pwJiwIWSckeCbOX8G12F4X.jpg',
    genre_ids: [28, 12, 16, 878],
    id: 324857,
    original_language: 'en',
    original_title: 'Spider-Man: Into the Spider-Verse',
    overview:
      'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
    popularity: 88.339,
    poster_path: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    release_date: '2018-12-06',
    title: 'Spider-Man: Into the Spider-Verse',
    video: false,
    vote_average: 8.4,
    vote_count: 11886,
  },
  {
    adult: false,
    backdrop_path: '/i1GT0e6Crg6UezT3ibXnMS3pBAd.jpg',
    genre_ids: [16, 18, 10749],
    id: 652837,
    original_language: 'ja',
    original_title: 'ジョゼと虎と魚たち',
    overview:
      'With dreams of diving abroad, Tsuneo gets a job assisting Josee, an artist whose imagination takes her far beyond her wheelchair. But when the tide turns against them, they push each other to places they never thought possible, and inspire a love fit for a storybook.',
    popularity: 70.996,
    poster_path: '/z1D8xi9x4uEhyFruo7uEHXUMD4K.jpg',
    release_date: '2020-12-25',
    title: 'Josee, the Tiger and the Fish',
    video: false,
    vote_average: 8.4,
    vote_count: 272,
  },
  {
    adult: false,
    backdrop_path: '/q5HZvtyqG8Vz39Ee9uTQbLeEml.jpg',
    genre_ids: [16, 18],
    id: 378064,
    original_language: 'ja',
    original_title: '映画 聲の形',
    overview:
      'Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?',
    popularity: 79.042,
    poster_path: '/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg',
    release_date: '2016-09-17',
    title: 'A Silent Voice: The Movie',
    video: false,
    vote_average: 8.4,
    vote_count: 3147,
  },
  {
    adult: false,
    backdrop_path: '/iuFbU5jiNh8DAxLBGifZCvv3KmB.jpg',
    genre_ids: [14, 16, 12],
    id: 4935,
    original_language: 'ja',
    original_title: 'ハウルの動く城',
    overview:
      'When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.',
    popularity: 87.733,
    poster_path: '/6pZgH10jhpToPcf0uvyTCPFhWpI.jpg',
    release_date: '2004-09-09',
    title: "Howl's Moving Castle",
    video: false,
    vote_average: 8.4,
    vote_count: 7704,
  },
  {
    adult: false,
    backdrop_path: '/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg',
    genre_ids: [12, 28, 878],
    id: 1891,
    original_language: 'en',
    original_title: 'The Empire Strikes Back',
    overview:
      'The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.',
    popularity: 29.704,
    poster_path: '/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg',
    release_date: '1980-05-20',
    title: 'The Empire Strikes Back',
    video: false,
    vote_average: 8.4,
    vote_count: 14685,
  },
  {
    adult: false,
    backdrop_path: '/hyaLMOol8xju70zr5glK6JaprER.jpg',
    genre_ids: [18, 16, 878, 28],
    id: 18491,
    original_language: 'ja',
    original_title: '新世紀エヴァンゲリオン劇場版 Air／まごころを、君に',
    overview:
      'The second of two theatrically released follow-ups to the Neon Genesis Evangelion series. Comprising of two alternate episodes which were first intended to take the place of episodes 25 and 26, this finale answers many of the questions surrounding the series, while also opening up some new possibilities.',
    popularity: 40.361,
    poster_path: '/j6G24dqI4WgUtChhWjfnI4lnmiK.jpg',
    release_date: '1997-07-19',
    title: 'Neon Genesis Evangelion: The End of Evangelion',
    video: false,
    vote_average: 8.4,
    vote_count: 1168,
  },
  {
    adult: false,
    backdrop_path: '/8GXkzHTvuj3ftethkrqW330LJKz.jpg',
    genre_ids: [10402],
    id: 568300,
    original_language: 'ko',
    original_title: '러브 유어셀프 인 서울',
    overview:
      'Shot at the Olympic Stadium in Seoul during the BTS World Tour ‘Love Yourself’ to celebrate the seven members of the global boyband and their unprecedented international phenomenon.',
    popularity: 8.464,
    poster_path: '/1u0rtWPgYfAWmqveXOsQDvMRODD.jpg',
    release_date: '2019-01-26',
    title: 'BTS World Tour: Love Yourself in Seoul',
    video: false,
    vote_average: 8.4,
    vote_count: 383,
  },
  {
    adult: false,
    backdrop_path: '/gU84vBGG2x8K3x1zrz4SggiN5hr.jpg',
    genre_ids: [12, 14, 28],
    id: 120,
    original_language: 'en',
    original_title: 'The Lord of the Rings: The Fellowship of the Ring',
    overview:
      'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.',
    popularity: 137.828,
    poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    release_date: '2001-12-18',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    video: false,
    vote_average: 8.4,
    vote_count: 21696,
  },
  {
    adult: false,
    backdrop_path: '/5QWHHjwIPoaJYHNVL0D00bxDUUC.jpg',
    genre_ids: [16, 14, 28, 12],
    id: 795607,
    original_language: 'zh',
    original_title: '白蛇 II: 青蛇劫起',
    overview:
      "While trying to free her sister from Fahai's clutches, Xiao Qing winds up in a dystopian city and meets a mysterious man who can't recall his past life.",
    popularity: 15.853,
    poster_path: '/aBGMJNuOLJO5bvFRBky4KMziQ4J.jpg',
    release_date: '2021-07-23',
    title: 'Green Snake',
    video: false,
    vote_average: 8.4,
    vote_count: 212,
  },
  {
    adult: false,
    backdrop_path: '/1EAxNqdkVnp48a7NUuNBHGflowM.jpg',
    genre_ids: [16, 28, 878, 18],
    id: 283566,
    original_language: 'ja',
    original_title: 'シン・エヴァンゲリオン劇場版:||',
    overview:
      'In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.',
    popularity: 58.117,
    poster_path: '/md5wZRRj8biHrGtyitgBZo7674t.jpg',
    release_date: '2021-03-08',
    title: 'Evangelion: 3.0+1.0 Thrice Upon a Time',
    video: false,
    vote_average: 8.4,
    vote_count: 574,
  },
  {
    adult: false,
    backdrop_path: '/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg',
    genre_ids: [18],
    id: 599,
    original_language: 'en',
    original_title: 'Sunset Boulevard',
    overview:
      'A hack screenwriter writes a screenplay for a former silent film star who has faded into Hollywood obscurity.',
    popularity: 12.949,
    poster_path: '/sC4Dpmn87oz9AuxZ15Lmip0Ftgr.jpg',
    release_date: '1950-08-10',
    title: 'Sunset Boulevard',
    video: false,
    vote_average: 8.4,
    vote_count: 2058,
  },
  {
    adult: false,
    backdrop_path: '/dVr11o9or7AS8AMPfwjSpEU83iU.jpg',
    genre_ids: [18, 10752],
    id: 423,
    original_language: 'en',
    original_title: 'The Pianist',
    overview:
      "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
    popularity: 44.35,
    poster_path: '/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
    release_date: '2002-09-17',
    title: 'The Pianist',
    video: false,
    vote_average: 8.4,
    vote_count: 7583,
  },
  {
    adult: false,
    backdrop_path: '/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg',
    genre_ids: [12, 18, 878],
    id: 157336,
    original_language: 'en',
    original_title: 'Interstellar',
    overview:
      'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    popularity: 143.472,
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    release_date: '2014-11-05',
    title: 'Interstellar',
    video: false,
    vote_average: 8.4,
    vote_count: 29630,
  },
  {
    adult: false,
    backdrop_path: '/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg',
    genre_ids: [18, 10402],
    id: 244786,
    original_language: 'en',
    original_title: 'Whiplash',
    overview:
      'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
    popularity: 54.828,
    poster_path: '/E1fpfU9cMCgFYL3QPvJr3vt20X.jpg',
    release_date: '2014-10-10',
    title: 'Whiplash',
    video: false,
    vote_average: 8.4,
    vote_count: 12673,
  },
  {
    adult: false,
    backdrop_path: '/wqgZSvgoctaadgwUdPYVsksivxn.jpg',
    genre_ids: [35, 18, 10749],
    id: 20334,
    original_language: 'en',
    original_title: 'The Shop Around the Corner',
    overview:
      "Two employees at a gift shop can barely stand one another, without realising that they are falling in love through the post as each other's anonymous pen pal.",
    popularity: 9.383,
    poster_path: '/dZ1aEzGYRiqJwPfjS6VL7wUkHmF.jpg',
    release_date: '1940-01-12',
    title: 'The Shop Around the Corner',
    video: false,
    vote_average: 8.4,
    vote_count: 545,
  },
  {
    adult: false,
    backdrop_path: '/kWYfW2Re0rUDE6IHhy4CRuKWeFr.jpg',
    genre_ids: [12, 14, 28],
    id: 121,
    original_language: 'en',
    original_title: 'The Lord of the Rings: The Two Towers',
    overview:
      'Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.',
    popularity: 133.372,
    poster_path: '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
    release_date: '2002-12-18',
    title: 'The Lord of the Rings: The Two Towers',
    video: false,
    vote_average: 8.4,
    vote_count: 18852,
  },
  {
    adult: false,
    backdrop_path: '/5qtOVAcBFogwktkseoZSfZVq6bx.jpg',
    genre_ids: [18],
    id: 3782,
    original_language: 'ja',
    original_title: '生きる',
    overview:
      'Kanji Watanabe is a middle-aged man who has worked in the same monotonous bureaucratic position for decades. Learning he has cancer, he starts to look for the meaning of his life.',
    popularity: 13.495,
    poster_path: '/dgNTS4EQDDVfkzJI5msKuHu2Ei3.jpg',
    release_date: '1952-10-09',
    title: 'Ikiru',
    video: false,
    vote_average: 8.4,
    vote_count: 838,
  },
  {
    adult: false,
    backdrop_path: '/9LSsSPbP715XT9B7acIZzantPyX.jpg',
    genre_ids: [18],
    id: 73,
    original_language: 'en',
    original_title: 'American History X',
    overview:
      "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
    popularity: 33.723,
    poster_path: '/c2gsmSQ2Cqv8zosqKOCwRS0GFBS.jpg',
    release_date: '1998-07-01',
    title: 'American History X',
    video: false,
    vote_average: 8.4,
    vote_count: 9929,
  },
  {
    adult: false,
    backdrop_path: '/zGs5tZOlvc9cprdcU6kDOVNpujf.jpg',
    genre_ids: [53, 9648],
    id: 567,
    original_language: 'en',
    original_title: 'Rear Window',
    overview:
      'A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.',
    popularity: 17.021,
    poster_path: '/qitnZcLP7C9DLRuPpmvZ7GiEjJN.jpg',
    release_date: '1954-08-01',
    title: 'Rear Window',
    video: false,
    vote_average: 8.4,
    vote_count: 5390,
  },
  {
    adult: false,
    backdrop_path: '/yHtB4KHNigx3ZoxDvQbW2SOXGfq.jpg',
    genre_ids: [16, 10751, 12, 14],
    id: 441130,
    original_language: 'en',
    original_title: 'Wolfwalkers',
    overview:
      'In a time of superstition and magic, when wolves are seen as demonic and nature an evil to be tamed, a young apprentice hunter comes to Ireland with her father to wipe out the last pack. But when she saves a wild native girl, their friendship leads her to discover the world of the Wolfwalkers and transform her into the very thing her father is tasked to destroy.',
    popularity: 19.116,
    poster_path: '/ehAKuE48okTuonq6TpsNQj8vFTC.jpg',
    release_date: '2020-10-26',
    title: 'Wolfwalkers',
    video: false,
    vote_average: 8.4,
    vote_count: 842,
  },
  {
    adult: false,
    backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    genre_ids: [28, 878, 12],
    id: 27205,
    original_language: 'en',
    original_title: 'Inception',
    overview:
      'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    popularity: 90.866,
    poster_path: '/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg',
    release_date: '2010-07-15',
    title: 'Inception',
    video: false,
    vote_average: 8.4,
    vote_count: 32490,
  },
  {
    adult: false,
    backdrop_path: '/hkKTtlHjiVUW5XRfkQfl3FmJUfX.jpg',
    genre_ids: [80, 9648, 53],
    id: 807,
    original_language: 'en',
    original_title: 'Se7en',
    overview:
      'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
    popularity: 45.207,
    poster_path: '/69Sns8WoET6CfaYlIkHbla4l7nC.jpg',
    release_date: '1995-09-22',
    title: 'Se7en',
    video: false,
    vote_average: 8.4,
    vote_count: 17791,
  },
  {
    adult: false,
    backdrop_path: '/aLqtWLA6NQHBwQHvHDq5z4EKUm0.jpg',
    genre_ids: [16, 14, 10749, 18],
    id: 533514,
    original_language: 'ja',
    original_title: '劇場版 ヴァイオレット・エヴァーガーデン',
    overview:
      'As the world moves on from the war and technological advances bring changes to her life, Violet still hopes to see her lost commanding officer again.',
    popularity: 75.46,
    poster_path: '/keDKycCcn3VgYvZhLnGiyYYtb2H.jpg',
    release_date: '2020-09-18',
    title: 'Violet Evergarden: The Movie',
    video: false,
    vote_average: 8.4,
    vote_count: 277,
  },
];
